### ISSUE TITLE
Release 0.7 Bugs

### ISSUE THREAD

**Issue by stojanov-igor** [UniversalDot/front-end#14]
1. If user inputs wrong organizational input we have get error thrown. 

```
Error handling:

Uncaught (in promise) Error: createType(Call):: Call: failed decoding dao.addTasks:: Struct: failed on args: {"org_id":"H256","task":"H256"}:: Struct: failed on org_id: H256:: Expected at least 32 bytes (256 bits), found 3 bytes
    at createTypeUnsafe (type.js:63:1)
    at TypeRegistry.createTypeUnsafe (registry.js:299:1)
    at extrinsicFn (createUnchecked.js:21:1)
    at Object.decorated [as addTasks] (Decorate.js:393:1)
    at signedTx (useDao.ts:322:1)
```

2. Check why memberof Returns only last organization, not all?
3. Refreshing page to get updates. 
4. Once task is accepted, remove it also from organizational task. 
5. Error handling. Task cant be Deleted if Completed.

**Comment by stojanov-igor** [comment]
@slaveatanasov I think all these have been fixed?

**Comment by stojanov-igor** [comment]
Fixed in substrate.. To be verified in new release.
